# Generated by Django 3.1 on 2020-08-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyuru_lang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.IntegerField(),
        ),
    ]
