# Generated by Django 3.1 on 2020-08-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyuru_lang', '0002_auto_20200814_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='votes',
            new_name='pyuru_string',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice_text',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='question_text',
        ),
        migrations.AddField(
            model_name='translation',
            name='translation_text',
            field=models.TextField(default='None', max_length=200),
        ),
    ]
